### PR TITLE
Moving librosa and scipy to optional install

### PR DESCRIPTION
**Pull request by csteinmetz1**
This could result in minor breaking changes for some users who are using melspectrogram-based losses or the FIR filter. However, this is likely a very small number of users and the there will be benefits to removing librosa which can cause issues on install on various platforms.

### CODE REVIEW

**Comment by csteinmetz1** [comment]
Users who want the above functionality should be able to install librosa and scipy with `pip install auraloss[all]`.

**Review by turian — APPROVED** [review]
LGTM

**Comment by turian** [comment]
@csteinmetz1 any idea when this might be live?

**Comment by csteinmetz1** [comment]
Looking to take this into main shortly (hopefully 1 week).

**Comment by turian** [comment]
I might be wrong but do you also need to edit `pyproject.toml`?

**Pull request merged**
